from setuptools import setup, find_packages

setup(
    name='qwen3-asr-toolkit',
    version='2.0.0',
    packages=find_packages(),
    include_package_data=True,
    package_data={
        'qwen_asr': ['inference/assets/*.dict'],
    },
    install_requires=[
        'openai',
        'librosa',
        'soundfile',
        'silero_vad',
        'pydub',
        'tqdm',
        'numpy',
        'srt',
        'requests',
        'fastapi',
        'uvicorn',
        'python-multipart',
        'websockets',
        'python-dotenv',
    ],
    extras_require={
        'qwen-asr': [
            'transformers==4.57.6',
            'nagisa==0.2.11',
            'soynlp==0.0.493',
            'accelerate==1.12.0',
            'qwen-omni-utils',
            'sox',
            'pytz',
            'gradio',
            'flask',
            'scipy',
        ],
        'qwen-asr-vllm': [
            'transformers==4.57.6',
            'nagisa==0.2.11',
            'soynlp==0.0.493',
            'accelerate==1.12.0',
            'qwen-omni-utils',
            'sox',
            'pytz',
            'gradio',
            'flask',
            'scipy',
            'vllm==0.14.0',
        ],
    },
    entry_points={
        'console_scripts': [
            'qwen3-asr=qwen3_asr_toolkit.call_api:main',
            'qwen3-asr-server=qwen3_asr_toolkit.server:main',
            'qwen3-asr-offline-cli=qwen3_asr_toolkit.offline_cli:main',
            'qwen3-asr-stream-cli=qwen3_asr_toolkit.realtime_cli:main',
            'qwen-asr-demo=qwen_asr.cli.demo:main',
            'qwen-asr-demo-streaming=qwen_asr.cli.demo_streaming:main',
            'qwen-asr-serve=qwen_asr.cli.serve:main',
        ]
    },
    author='He Wang',
    author_email='hwang2001@mail.nwpu.edu.cn',
    description='Python toolkit for the Qwen3-ASR API—parallel high‑throughput calls, robust long‑audio transcription, multi‑sample‑rate support.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/QwenLM/Qwen3-ASR-Toolkit',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.8',
)
